// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	adapters "github.com/xmbshwll/ariadne/internal/adapters"

	mock "github.com/stretchr/testify/mock"

	model "github.com/xmbshwll/ariadne/internal/model"
)

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// Capabilities provides a mock function with no fields
func (_m *MockAdapter) Capabilities() adapters.Capabilities {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Capabilities")
	}

	var r0 adapters.Capabilities
	if rf, ok := ret.Get(0).(func() adapters.Capabilities); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(adapters.Capabilities)
	}

	return r0
}

// MockAdapter_Capabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capabilities'
type MockAdapter_Capabilities_Call struct {
	*mock.Call
}

// Capabilities is a helper method to define mock.On call
func (_e *MockAdapter_Expecter) Capabilities() *MockAdapter_Capabilities_Call {
	return &MockAdapter_Capabilities_Call{Call: _e.mock.On("Capabilities")}
}

func (_c *MockAdapter_Capabilities_Call) Run(run func()) *MockAdapter_Capabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdapter_Capabilities_Call) Return(_a0 adapters.Capabilities) *MockAdapter_Capabilities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdapter_Capabilities_Call) RunAndReturn(run func() adapters.Capabilities) *MockAdapter_Capabilities_Call {
	_c.Call.Return(run)
	return _c
}

// FetchAlbum provides a mock function with given fields: ctx, parsed
func (_m *MockAdapter) FetchAlbum(ctx context.Context, parsed model.ParsedAlbumURL) (*model.CanonicalAlbum, error) {
	ret := _m.Called(ctx, parsed)

	if len(ret) == 0 {
		panic("no return value specified for FetchAlbum")
	}

	var r0 *model.CanonicalAlbum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ParsedAlbumURL) (*model.CanonicalAlbum, error)); ok {
		return rf(ctx, parsed)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ParsedAlbumURL) *model.CanonicalAlbum); ok {
		r0 = rf(ctx, parsed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CanonicalAlbum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ParsedAlbumURL) error); ok {
		r1 = rf(ctx, parsed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_FetchAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAlbum'
type MockAdapter_FetchAlbum_Call struct {
	*mock.Call
}

// FetchAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - parsed model.ParsedAlbumURL
func (_e *MockAdapter_Expecter) FetchAlbum(ctx interface{}, parsed interface{}) *MockAdapter_FetchAlbum_Call {
	return &MockAdapter_FetchAlbum_Call{Call: _e.mock.On("FetchAlbum", ctx, parsed)}
}

func (_c *MockAdapter_FetchAlbum_Call) Run(run func(ctx context.Context, parsed model.ParsedAlbumURL)) *MockAdapter_FetchAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ParsedAlbumURL))
	})
	return _c
}

func (_c *MockAdapter_FetchAlbum_Call) Return(_a0 *model.CanonicalAlbum, _a1 error) *MockAdapter_FetchAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_FetchAlbum_Call) RunAndReturn(run func(context.Context, model.ParsedAlbumURL) (*model.CanonicalAlbum, error)) *MockAdapter_FetchAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// FetchSong provides a mock function with given fields: ctx, parsed
func (_m *MockAdapter) FetchSong(ctx context.Context, parsed model.ParsedURL) (*model.CanonicalSong, error) {
	ret := _m.Called(ctx, parsed)

	if len(ret) == 0 {
		panic("no return value specified for FetchSong")
	}

	var r0 *model.CanonicalSong
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ParsedURL) (*model.CanonicalSong, error)); ok {
		return rf(ctx, parsed)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ParsedURL) *model.CanonicalSong); ok {
		r0 = rf(ctx, parsed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CanonicalSong)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ParsedURL) error); ok {
		r1 = rf(ctx, parsed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_FetchSong_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchSong'
type MockAdapter_FetchSong_Call struct {
	*mock.Call
}

// FetchSong is a helper method to define mock.On call
//   - ctx context.Context
//   - parsed model.ParsedURL
func (_e *MockAdapter_Expecter) FetchSong(ctx interface{}, parsed interface{}) *MockAdapter_FetchSong_Call {
	return &MockAdapter_FetchSong_Call{Call: _e.mock.On("FetchSong", ctx, parsed)}
}

func (_c *MockAdapter_FetchSong_Call) Run(run func(ctx context.Context, parsed model.ParsedURL)) *MockAdapter_FetchSong_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ParsedURL))
	})
	return _c
}

func (_c *MockAdapter_FetchSong_Call) Return(_a0 *model.CanonicalSong, _a1 error) *MockAdapter_FetchSong_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_FetchSong_Call) RunAndReturn(run func(context.Context, model.ParsedURL) (*model.CanonicalSong, error)) *MockAdapter_FetchSong_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAlbumURL provides a mock function with given fields: raw
func (_m *MockAdapter) ParseAlbumURL(raw string) (*model.ParsedAlbumURL, error) {
	ret := _m.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for ParseAlbumURL")
	}

	var r0 *model.ParsedAlbumURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ParsedAlbumURL, error)); ok {
		return rf(raw)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ParsedAlbumURL); ok {
		r0 = rf(raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ParsedAlbumURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(raw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_ParseAlbumURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAlbumURL'
type MockAdapter_ParseAlbumURL_Call struct {
	*mock.Call
}

// ParseAlbumURL is a helper method to define mock.On call
//   - raw string
func (_e *MockAdapter_Expecter) ParseAlbumURL(raw interface{}) *MockAdapter_ParseAlbumURL_Call {
	return &MockAdapter_ParseAlbumURL_Call{Call: _e.mock.On("ParseAlbumURL", raw)}
}

func (_c *MockAdapter_ParseAlbumURL_Call) Run(run func(raw string)) *MockAdapter_ParseAlbumURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAdapter_ParseAlbumURL_Call) Return(_a0 *model.ParsedAlbumURL, _a1 error) *MockAdapter_ParseAlbumURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_ParseAlbumURL_Call) RunAndReturn(run func(string) (*model.ParsedAlbumURL, error)) *MockAdapter_ParseAlbumURL_Call {
	_c.Call.Return(run)
	return _c
}

// ParseSongURL provides a mock function with given fields: raw
func (_m *MockAdapter) ParseSongURL(raw string) (*model.ParsedURL, error) {
	ret := _m.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for ParseSongURL")
	}

	var r0 *model.ParsedURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ParsedURL, error)); ok {
		return rf(raw)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ParsedURL); ok {
		r0 = rf(raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ParsedURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(raw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_ParseSongURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseSongURL'
type MockAdapter_ParseSongURL_Call struct {
	*mock.Call
}

// ParseSongURL is a helper method to define mock.On call
//   - raw string
func (_e *MockAdapter_Expecter) ParseSongURL(raw interface{}) *MockAdapter_ParseSongURL_Call {
	return &MockAdapter_ParseSongURL_Call{Call: _e.mock.On("ParseSongURL", raw)}
}

func (_c *MockAdapter_ParseSongURL_Call) Run(run func(raw string)) *MockAdapter_ParseSongURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAdapter_ParseSongURL_Call) Return(_a0 *model.ParsedURL, _a1 error) *MockAdapter_ParseSongURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_ParseSongURL_Call) RunAndReturn(run func(string) (*model.ParsedURL, error)) *MockAdapter_ParseSongURL_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAlbumByISRC provides a mock function with given fields: ctx, isrcs
func (_m *MockAdapter) SearchAlbumByISRC(ctx context.Context, isrcs []string) ([]model.CandidateAlbum, error) {
	ret := _m.Called(ctx, isrcs)

	if len(ret) == 0 {
		panic("no return value specified for SearchAlbumByISRC")
	}

	var r0 []model.CandidateAlbum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]model.CandidateAlbum, error)); ok {
		return rf(ctx, isrcs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []model.CandidateAlbum); ok {
		r0 = rf(ctx, isrcs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CandidateAlbum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, isrcs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_SearchAlbumByISRC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAlbumByISRC'
type MockAdapter_SearchAlbumByISRC_Call struct {
	*mock.Call
}

// SearchAlbumByISRC is a helper method to define mock.On call
//   - ctx context.Context
//   - isrcs []string
func (_e *MockAdapter_Expecter) SearchAlbumByISRC(ctx interface{}, isrcs interface{}) *MockAdapter_SearchAlbumByISRC_Call {
	return &MockAdapter_SearchAlbumByISRC_Call{Call: _e.mock.On("SearchAlbumByISRC", ctx, isrcs)}
}

func (_c *MockAdapter_SearchAlbumByISRC_Call) Run(run func(ctx context.Context, isrcs []string)) *MockAdapter_SearchAlbumByISRC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockAdapter_SearchAlbumByISRC_Call) Return(_a0 []model.CandidateAlbum, _a1 error) *MockAdapter_SearchAlbumByISRC_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_SearchAlbumByISRC_Call) RunAndReturn(run func(context.Context, []string) ([]model.CandidateAlbum, error)) *MockAdapter_SearchAlbumByISRC_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAlbumByMetadata provides a mock function with given fields: ctx, album
func (_m *MockAdapter) SearchAlbumByMetadata(ctx context.Context, album model.CanonicalAlbum) ([]model.CandidateAlbum, error) {
	ret := _m.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for SearchAlbumByMetadata")
	}

	var r0 []model.CandidateAlbum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CanonicalAlbum) ([]model.CandidateAlbum, error)); ok {
		return rf(ctx, album)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CanonicalAlbum) []model.CandidateAlbum); ok {
		r0 = rf(ctx, album)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CandidateAlbum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CanonicalAlbum) error); ok {
		r1 = rf(ctx, album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_SearchAlbumByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAlbumByMetadata'
type MockAdapter_SearchAlbumByMetadata_Call struct {
	*mock.Call
}

// SearchAlbumByMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - album model.CanonicalAlbum
func (_e *MockAdapter_Expecter) SearchAlbumByMetadata(ctx interface{}, album interface{}) *MockAdapter_SearchAlbumByMetadata_Call {
	return &MockAdapter_SearchAlbumByMetadata_Call{Call: _e.mock.On("SearchAlbumByMetadata", ctx, album)}
}

func (_c *MockAdapter_SearchAlbumByMetadata_Call) Run(run func(ctx context.Context, album model.CanonicalAlbum)) *MockAdapter_SearchAlbumByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CanonicalAlbum))
	})
	return _c
}

func (_c *MockAdapter_SearchAlbumByMetadata_Call) Return(_a0 []model.CandidateAlbum, _a1 error) *MockAdapter_SearchAlbumByMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_SearchAlbumByMetadata_Call) RunAndReturn(run func(context.Context, model.CanonicalAlbum) ([]model.CandidateAlbum, error)) *MockAdapter_SearchAlbumByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAlbumByUPC provides a mock function with given fields: ctx, upc
func (_m *MockAdapter) SearchAlbumByUPC(ctx context.Context, upc string) ([]model.CandidateAlbum, error) {
	ret := _m.Called(ctx, upc)

	if len(ret) == 0 {
		panic("no return value specified for SearchAlbumByUPC")
	}

	var r0 []model.CandidateAlbum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.CandidateAlbum, error)); ok {
		return rf(ctx, upc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.CandidateAlbum); ok {
		r0 = rf(ctx, upc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CandidateAlbum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, upc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_SearchAlbumByUPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAlbumByUPC'
type MockAdapter_SearchAlbumByUPC_Call struct {
	*mock.Call
}

// SearchAlbumByUPC is a helper method to define mock.On call
//   - ctx context.Context
//   - upc string
func (_e *MockAdapter_Expecter) SearchAlbumByUPC(ctx interface{}, upc interface{}) *MockAdapter_SearchAlbumByUPC_Call {
	return &MockAdapter_SearchAlbumByUPC_Call{Call: _e.mock.On("SearchAlbumByUPC", ctx, upc)}
}

func (_c *MockAdapter_SearchAlbumByUPC_Call) Run(run func(ctx context.Context, upc string)) *MockAdapter_SearchAlbumByUPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdapter_SearchAlbumByUPC_Call) Return(_a0 []model.CandidateAlbum, _a1 error) *MockAdapter_SearchAlbumByUPC_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_SearchAlbumByUPC_Call) RunAndReturn(run func(context.Context, string) ([]model.CandidateAlbum, error)) *MockAdapter_SearchAlbumByUPC_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSongByISRC provides a mock function with given fields: ctx, isrc
func (_m *MockAdapter) SearchSongByISRC(ctx context.Context, isrc string) ([]model.CandidateSong, error) {
	ret := _m.Called(ctx, isrc)

	if len(ret) == 0 {
		panic("no return value specified for SearchSongByISRC")
	}

	var r0 []model.CandidateSong
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.CandidateSong, error)); ok {
		return rf(ctx, isrc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.CandidateSong); ok {
		r0 = rf(ctx, isrc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CandidateSong)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isrc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_SearchSongByISRC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSongByISRC'
type MockAdapter_SearchSongByISRC_Call struct {
	*mock.Call
}

// SearchSongByISRC is a helper method to define mock.On call
//   - ctx context.Context
//   - isrc string
func (_e *MockAdapter_Expecter) SearchSongByISRC(ctx interface{}, isrc interface{}) *MockAdapter_SearchSongByISRC_Call {
	return &MockAdapter_SearchSongByISRC_Call{Call: _e.mock.On("SearchSongByISRC", ctx, isrc)}
}

func (_c *MockAdapter_SearchSongByISRC_Call) Run(run func(ctx context.Context, isrc string)) *MockAdapter_SearchSongByISRC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdapter_SearchSongByISRC_Call) Return(_a0 []model.CandidateSong, _a1 error) *MockAdapter_SearchSongByISRC_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_SearchSongByISRC_Call) RunAndReturn(run func(context.Context, string) ([]model.CandidateSong, error)) *MockAdapter_SearchSongByISRC_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSongByMetadata provides a mock function with given fields: ctx, song
func (_m *MockAdapter) SearchSongByMetadata(ctx context.Context, song model.CanonicalSong) ([]model.CandidateSong, error) {
	ret := _m.Called(ctx, song)

	if len(ret) == 0 {
		panic("no return value specified for SearchSongByMetadata")
	}

	var r0 []model.CandidateSong
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CanonicalSong) ([]model.CandidateSong, error)); ok {
		return rf(ctx, song)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CanonicalSong) []model.CandidateSong); ok {
		r0 = rf(ctx, song)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CandidateSong)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CanonicalSong) error); ok {
		r1 = rf(ctx, song)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdapter_SearchSongByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSongByMetadata'
type MockAdapter_SearchSongByMetadata_Call struct {
	*mock.Call
}

// SearchSongByMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - song model.CanonicalSong
func (_e *MockAdapter_Expecter) SearchSongByMetadata(ctx interface{}, song interface{}) *MockAdapter_SearchSongByMetadata_Call {
	return &MockAdapter_SearchSongByMetadata_Call{Call: _e.mock.On("SearchSongByMetadata", ctx, song)}
}

func (_c *MockAdapter_SearchSongByMetadata_Call) Run(run func(ctx context.Context, song model.CanonicalSong)) *MockAdapter_SearchSongByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CanonicalSong))
	})
	return _c
}

func (_c *MockAdapter_SearchSongByMetadata_Call) Return(_a0 []model.CandidateSong, _a1 error) *MockAdapter_SearchSongByMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdapter_SearchSongByMetadata_Call) RunAndReturn(run func(context.Context, model.CanonicalSong) ([]model.CandidateSong, error)) *MockAdapter_SearchSongByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Service provides a mock function with no fields
func (_m *MockAdapter) Service() model.ServiceName {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Service")
	}

	var r0 model.ServiceName
	if rf, ok := ret.Get(0).(func() model.ServiceName); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.ServiceName)
	}

	return r0
}

// MockAdapter_Service_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Service'
type MockAdapter_Service_Call struct {
	*mock.Call
}

// Service is a helper method to define mock.On call
func (_e *MockAdapter_Expecter) Service() *MockAdapter_Service_Call {
	return &MockAdapter_Service_Call{Call: _e.mock.On("Service")}
}

func (_c *MockAdapter_Service_Call) Run(run func()) *MockAdapter_Service_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdapter_Service_Call) Return(_a0 model.ServiceName) *MockAdapter_Service_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdapter_Service_Call) RunAndReturn(run func() model.ServiceName) *MockAdapter_Service_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
