// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/xmbshwll/ariadne/internal/model"
)

// MockAlbumTargetSearcher is an autogenerated mock type for the AlbumTargetSearcher type
type MockAlbumTargetSearcher struct {
	mock.Mock
}

type MockAlbumTargetSearcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAlbumTargetSearcher) EXPECT() *MockAlbumTargetSearcher_Expecter {
	return &MockAlbumTargetSearcher_Expecter{mock: &_m.Mock}
}

// SearchByISRC provides a mock function with given fields: ctx, isrcs
func (_m *MockAlbumTargetSearcher) SearchByISRC(ctx context.Context, isrcs []string) ([]model.CandidateAlbum, error) {
	ret := _m.Called(ctx, isrcs)

	if len(ret) == 0 {
		panic("no return value specified for SearchByISRC")
	}

	var r0 []model.CandidateAlbum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]model.CandidateAlbum, error)); ok {
		return rf(ctx, isrcs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []model.CandidateAlbum); ok {
		r0 = rf(ctx, isrcs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CandidateAlbum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, isrcs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumTargetSearcher_SearchByISRC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByISRC'
type MockAlbumTargetSearcher_SearchByISRC_Call struct {
	*mock.Call
}

// SearchByISRC is a helper method to define mock.On call
//   - ctx context.Context
//   - isrcs []string
func (_e *MockAlbumTargetSearcher_Expecter) SearchByISRC(ctx interface{}, isrcs interface{}) *MockAlbumTargetSearcher_SearchByISRC_Call {
	return &MockAlbumTargetSearcher_SearchByISRC_Call{Call: _e.mock.On("SearchByISRC", ctx, isrcs)}
}

func (_c *MockAlbumTargetSearcher_SearchByISRC_Call) Run(run func(ctx context.Context, isrcs []string)) *MockAlbumTargetSearcher_SearchByISRC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockAlbumTargetSearcher_SearchByISRC_Call) Return(_a0 []model.CandidateAlbum, _a1 error) *MockAlbumTargetSearcher_SearchByISRC_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumTargetSearcher_SearchByISRC_Call) RunAndReturn(run func(context.Context, []string) ([]model.CandidateAlbum, error)) *MockAlbumTargetSearcher_SearchByISRC_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByMetadata provides a mock function with given fields: ctx, album
func (_m *MockAlbumTargetSearcher) SearchByMetadata(ctx context.Context, album model.CanonicalAlbum) ([]model.CandidateAlbum, error) {
	ret := _m.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for SearchByMetadata")
	}

	var r0 []model.CandidateAlbum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CanonicalAlbum) ([]model.CandidateAlbum, error)); ok {
		return rf(ctx, album)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CanonicalAlbum) []model.CandidateAlbum); ok {
		r0 = rf(ctx, album)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CandidateAlbum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CanonicalAlbum) error); ok {
		r1 = rf(ctx, album)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumTargetSearcher_SearchByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByMetadata'
type MockAlbumTargetSearcher_SearchByMetadata_Call struct {
	*mock.Call
}

// SearchByMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - album model.CanonicalAlbum
func (_e *MockAlbumTargetSearcher_Expecter) SearchByMetadata(ctx interface{}, album interface{}) *MockAlbumTargetSearcher_SearchByMetadata_Call {
	return &MockAlbumTargetSearcher_SearchByMetadata_Call{Call: _e.mock.On("SearchByMetadata", ctx, album)}
}

func (_c *MockAlbumTargetSearcher_SearchByMetadata_Call) Run(run func(ctx context.Context, album model.CanonicalAlbum)) *MockAlbumTargetSearcher_SearchByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CanonicalAlbum))
	})
	return _c
}

func (_c *MockAlbumTargetSearcher_SearchByMetadata_Call) Return(_a0 []model.CandidateAlbum, _a1 error) *MockAlbumTargetSearcher_SearchByMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumTargetSearcher_SearchByMetadata_Call) RunAndReturn(run func(context.Context, model.CanonicalAlbum) ([]model.CandidateAlbum, error)) *MockAlbumTargetSearcher_SearchByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByUPC provides a mock function with given fields: ctx, upc
func (_m *MockAlbumTargetSearcher) SearchByUPC(ctx context.Context, upc string) ([]model.CandidateAlbum, error) {
	ret := _m.Called(ctx, upc)

	if len(ret) == 0 {
		panic("no return value specified for SearchByUPC")
	}

	var r0 []model.CandidateAlbum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.CandidateAlbum, error)); ok {
		return rf(ctx, upc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.CandidateAlbum); ok {
		r0 = rf(ctx, upc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CandidateAlbum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, upc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAlbumTargetSearcher_SearchByUPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByUPC'
type MockAlbumTargetSearcher_SearchByUPC_Call struct {
	*mock.Call
}

// SearchByUPC is a helper method to define mock.On call
//   - ctx context.Context
//   - upc string
func (_e *MockAlbumTargetSearcher_Expecter) SearchByUPC(ctx interface{}, upc interface{}) *MockAlbumTargetSearcher_SearchByUPC_Call {
	return &MockAlbumTargetSearcher_SearchByUPC_Call{Call: _e.mock.On("SearchByUPC", ctx, upc)}
}

func (_c *MockAlbumTargetSearcher_SearchByUPC_Call) Run(run func(ctx context.Context, upc string)) *MockAlbumTargetSearcher_SearchByUPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAlbumTargetSearcher_SearchByUPC_Call) Return(_a0 []model.CandidateAlbum, _a1 error) *MockAlbumTargetSearcher_SearchByUPC_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAlbumTargetSearcher_SearchByUPC_Call) RunAndReturn(run func(context.Context, string) ([]model.CandidateAlbum, error)) *MockAlbumTargetSearcher_SearchByUPC_Call {
	_c.Call.Return(run)
	return _c
}

// Service provides a mock function with no fields
func (_m *MockAlbumTargetSearcher) Service() model.ServiceName {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Service")
	}

	var r0 model.ServiceName
	if rf, ok := ret.Get(0).(func() model.ServiceName); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.ServiceName)
	}

	return r0
}

// MockAlbumTargetSearcher_Service_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Service'
type MockAlbumTargetSearcher_Service_Call struct {
	*mock.Call
}

// Service is a helper method to define mock.On call
func (_e *MockAlbumTargetSearcher_Expecter) Service() *MockAlbumTargetSearcher_Service_Call {
	return &MockAlbumTargetSearcher_Service_Call{Call: _e.mock.On("Service")}
}

func (_c *MockAlbumTargetSearcher_Service_Call) Run(run func()) *MockAlbumTargetSearcher_Service_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAlbumTargetSearcher_Service_Call) Return(_a0 model.ServiceName) *MockAlbumTargetSearcher_Service_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAlbumTargetSearcher_Service_Call) RunAndReturn(run func() model.ServiceName) *MockAlbumTargetSearcher_Service_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAlbumTargetSearcher creates a new instance of MockAlbumTargetSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlbumTargetSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlbumTargetSearcher {
	mock := &MockAlbumTargetSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
