version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - dupword
    - errcheck
    - errorlint
    - exptostd
    - goconst
    - gocritic
    - godot
    - intrange
    - err113
    - misspell
    - modernize
    - perfsprint
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - predeclared
    - revive
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - wrapcheck
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    misspell:
      locale: US
      ignore-rules:
        - Catalogue
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
