with-expecter: true
disable-version-string: true
issue-845-fix: true
resolve-type-alias: false

_anchors: &mockery_inpackage
  dir: "{{.InterfaceDir}}"
  filename: "{{.InterfaceNameSnake}}_mock_test.go"
  mockname: "Mock{{.InterfaceName}}"
  outpkg: "{{.PackageName}}"
  inpackage: true
  testonly: true

packages:
  github.com/xmbshwll/ariadne:
    config: *mockery_inpackage
    interfaces:
      SourceAdapter:
      TargetAdapter:
      SongSourceAdapter:
      SongTargetAdapter:
  github.com/xmbshwll/ariadne/internal/resolve:
    config: *mockery_inpackage
    interfaces:
      SourceAdapter:
      TargetAdapter:
      SongSourceAdapter:
      SongTargetAdapter:
