// Code generated by mockery. DO NOT EDIT.

package ariadne

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSongTargetAdapter is an autogenerated mock type for the SongTargetAdapter type
type MockSongTargetAdapter struct {
	mock.Mock
}

type MockSongTargetAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSongTargetAdapter) EXPECT() *MockSongTargetAdapter_Expecter {
	return &MockSongTargetAdapter_Expecter{mock: &_m.Mock}
}

// SearchSongByISRC provides a mock function with given fields: ctx, isrc
func (_m *MockSongTargetAdapter) SearchSongByISRC(ctx context.Context, isrc string) ([]CandidateSong, error) {
	ret := _m.Called(ctx, isrc)

	if len(ret) == 0 {
		panic("no return value specified for SearchSongByISRC")
	}

	var r0 []CandidateSong
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]CandidateSong, error)); ok {
		return rf(ctx, isrc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []CandidateSong); ok {
		r0 = rf(ctx, isrc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]CandidateSong)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, isrc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSongTargetAdapter_SearchSongByISRC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSongByISRC'
type MockSongTargetAdapter_SearchSongByISRC_Call struct {
	*mock.Call
}

// SearchSongByISRC is a helper method to define mock.On call
//   - ctx context.Context
//   - isrc string
func (_e *MockSongTargetAdapter_Expecter) SearchSongByISRC(ctx interface{}, isrc interface{}) *MockSongTargetAdapter_SearchSongByISRC_Call {
	return &MockSongTargetAdapter_SearchSongByISRC_Call{Call: _e.mock.On("SearchSongByISRC", ctx, isrc)}
}

func (_c *MockSongTargetAdapter_SearchSongByISRC_Call) Run(run func(ctx context.Context, isrc string)) *MockSongTargetAdapter_SearchSongByISRC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSongTargetAdapter_SearchSongByISRC_Call) Return(_a0 []CandidateSong, _a1 error) *MockSongTargetAdapter_SearchSongByISRC_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSongTargetAdapter_SearchSongByISRC_Call) RunAndReturn(run func(context.Context, string) ([]CandidateSong, error)) *MockSongTargetAdapter_SearchSongByISRC_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSongByMetadata provides a mock function with given fields: ctx, song
func (_m *MockSongTargetAdapter) SearchSongByMetadata(ctx context.Context, song CanonicalSong) ([]CandidateSong, error) {
	ret := _m.Called(ctx, song)

	if len(ret) == 0 {
		panic("no return value specified for SearchSongByMetadata")
	}

	var r0 []CandidateSong
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CanonicalSong) ([]CandidateSong, error)); ok {
		return rf(ctx, song)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CanonicalSong) []CandidateSong); ok {
		r0 = rf(ctx, song)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]CandidateSong)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CanonicalSong) error); ok {
		r1 = rf(ctx, song)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSongTargetAdapter_SearchSongByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSongByMetadata'
type MockSongTargetAdapter_SearchSongByMetadata_Call struct {
	*mock.Call
}

// SearchSongByMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - song CanonicalSong
func (_e *MockSongTargetAdapter_Expecter) SearchSongByMetadata(ctx interface{}, song interface{}) *MockSongTargetAdapter_SearchSongByMetadata_Call {
	return &MockSongTargetAdapter_SearchSongByMetadata_Call{Call: _e.mock.On("SearchSongByMetadata", ctx, song)}
}

func (_c *MockSongTargetAdapter_SearchSongByMetadata_Call) Run(run func(ctx context.Context, song CanonicalSong)) *MockSongTargetAdapter_SearchSongByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CanonicalSong))
	})
	return _c
}

func (_c *MockSongTargetAdapter_SearchSongByMetadata_Call) Return(_a0 []CandidateSong, _a1 error) *MockSongTargetAdapter_SearchSongByMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSongTargetAdapter_SearchSongByMetadata_Call) RunAndReturn(run func(context.Context, CanonicalSong) ([]CandidateSong, error)) *MockSongTargetAdapter_SearchSongByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Service provides a mock function with no fields
func (_m *MockSongTargetAdapter) Service() ServiceName {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Service")
	}

	var r0 ServiceName
	if rf, ok := ret.Get(0).(func() ServiceName); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ServiceName)
	}

	return r0
}

// MockSongTargetAdapter_Service_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Service'
type MockSongTargetAdapter_Service_Call struct {
	*mock.Call
}

// Service is a helper method to define mock.On call
func (_e *MockSongTargetAdapter_Expecter) Service() *MockSongTargetAdapter_Service_Call {
	return &MockSongTargetAdapter_Service_Call{Call: _e.mock.On("Service")}
}

func (_c *MockSongTargetAdapter_Service_Call) Run(run func()) *MockSongTargetAdapter_Service_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSongTargetAdapter_Service_Call) Return(_a0 ServiceName) *MockSongTargetAdapter_Service_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSongTargetAdapter_Service_Call) RunAndReturn(run func() ServiceName) *MockSongTargetAdapter_Service_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSongTargetAdapter creates a new instance of MockSongTargetAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSongTargetAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSongTargetAdapter {
	mock := &MockSongTargetAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
