// Code generated by mockery. DO NOT EDIT.

package resolve

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/xmbshwll/ariadne/internal/model"
)

// MockSongSourceAdapter is an autogenerated mock type for the SongSourceAdapter type
type MockSongSourceAdapter struct {
	mock.Mock
}

type MockSongSourceAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSongSourceAdapter) EXPECT() *MockSongSourceAdapter_Expecter {
	return &MockSongSourceAdapter_Expecter{mock: &_m.Mock}
}

// FetchSong provides a mock function with given fields: ctx, parsed
func (_m *MockSongSourceAdapter) FetchSong(ctx context.Context, parsed model.ParsedURL) (*model.CanonicalSong, error) {
	ret := _m.Called(ctx, parsed)

	if len(ret) == 0 {
		panic("no return value specified for FetchSong")
	}

	var r0 *model.CanonicalSong
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ParsedURL) (*model.CanonicalSong, error)); ok {
		return rf(ctx, parsed)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ParsedURL) *model.CanonicalSong); ok {
		r0 = rf(ctx, parsed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CanonicalSong)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ParsedURL) error); ok {
		r1 = rf(ctx, parsed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSongSourceAdapter_FetchSong_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchSong'
type MockSongSourceAdapter_FetchSong_Call struct {
	*mock.Call
}

// FetchSong is a helper method to define mock.On call
//   - ctx context.Context
//   - parsed model.ParsedURL
func (_e *MockSongSourceAdapter_Expecter) FetchSong(ctx interface{}, parsed interface{}) *MockSongSourceAdapter_FetchSong_Call {
	return &MockSongSourceAdapter_FetchSong_Call{Call: _e.mock.On("FetchSong", ctx, parsed)}
}

func (_c *MockSongSourceAdapter_FetchSong_Call) Run(run func(ctx context.Context, parsed model.ParsedURL)) *MockSongSourceAdapter_FetchSong_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ParsedURL))
	})
	return _c
}

func (_c *MockSongSourceAdapter_FetchSong_Call) Return(_a0 *model.CanonicalSong, _a1 error) *MockSongSourceAdapter_FetchSong_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSongSourceAdapter_FetchSong_Call) RunAndReturn(run func(context.Context, model.ParsedURL) (*model.CanonicalSong, error)) *MockSongSourceAdapter_FetchSong_Call {
	_c.Call.Return(run)
	return _c
}

// ParseSongURL provides a mock function with given fields: raw
func (_m *MockSongSourceAdapter) ParseSongURL(raw string) (*model.ParsedURL, error) {
	ret := _m.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for ParseSongURL")
	}

	var r0 *model.ParsedURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ParsedURL, error)); ok {
		return rf(raw)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ParsedURL); ok {
		r0 = rf(raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ParsedURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(raw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSongSourceAdapter_ParseSongURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseSongURL'
type MockSongSourceAdapter_ParseSongURL_Call struct {
	*mock.Call
}

// ParseSongURL is a helper method to define mock.On call
//   - raw string
func (_e *MockSongSourceAdapter_Expecter) ParseSongURL(raw interface{}) *MockSongSourceAdapter_ParseSongURL_Call {
	return &MockSongSourceAdapter_ParseSongURL_Call{Call: _e.mock.On("ParseSongURL", raw)}
}

func (_c *MockSongSourceAdapter_ParseSongURL_Call) Run(run func(raw string)) *MockSongSourceAdapter_ParseSongURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSongSourceAdapter_ParseSongURL_Call) Return(_a0 *model.ParsedURL, _a1 error) *MockSongSourceAdapter_ParseSongURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSongSourceAdapter_ParseSongURL_Call) RunAndReturn(run func(string) (*model.ParsedURL, error)) *MockSongSourceAdapter_ParseSongURL_Call {
	_c.Call.Return(run)
	return _c
}

// Service provides a mock function with no fields
func (_m *MockSongSourceAdapter) Service() model.ServiceName {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Service")
	}

	var r0 model.ServiceName
	if rf, ok := ret.Get(0).(func() model.ServiceName); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.ServiceName)
	}

	return r0
}

// MockSongSourceAdapter_Service_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Service'
type MockSongSourceAdapter_Service_Call struct {
	*mock.Call
}

// Service is a helper method to define mock.On call
func (_e *MockSongSourceAdapter_Expecter) Service() *MockSongSourceAdapter_Service_Call {
	return &MockSongSourceAdapter_Service_Call{Call: _e.mock.On("Service")}
}

func (_c *MockSongSourceAdapter_Service_Call) Run(run func()) *MockSongSourceAdapter_Service_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSongSourceAdapter_Service_Call) Return(_a0 model.ServiceName) *MockSongSourceAdapter_Service_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSongSourceAdapter_Service_Call) RunAndReturn(run func() model.ServiceName) *MockSongSourceAdapter_Service_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSongSourceAdapter creates a new instance of MockSongSourceAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSongSourceAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSongSourceAdapter {
	mock := &MockSongSourceAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
