// Code generated by mockery. DO NOT EDIT.

package resolve

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/xmbshwll/ariadne/internal/model"
)

// MockSourceAdapter is an autogenerated mock type for the SourceAdapter type
type MockSourceAdapter struct {
	mock.Mock
}

type MockSourceAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSourceAdapter) EXPECT() *MockSourceAdapter_Expecter {
	return &MockSourceAdapter_Expecter{mock: &_m.Mock}
}

// FetchAlbum provides a mock function with given fields: ctx, parsed
func (_m *MockSourceAdapter) FetchAlbum(ctx context.Context, parsed model.ParsedAlbumURL) (*model.CanonicalAlbum, error) {
	ret := _m.Called(ctx, parsed)

	if len(ret) == 0 {
		panic("no return value specified for FetchAlbum")
	}

	var r0 *model.CanonicalAlbum
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ParsedAlbumURL) (*model.CanonicalAlbum, error)); ok {
		return rf(ctx, parsed)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ParsedAlbumURL) *model.CanonicalAlbum); ok {
		r0 = rf(ctx, parsed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CanonicalAlbum)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ParsedAlbumURL) error); ok {
		r1 = rf(ctx, parsed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceAdapter_FetchAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAlbum'
type MockSourceAdapter_FetchAlbum_Call struct {
	*mock.Call
}

// FetchAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - parsed model.ParsedAlbumURL
func (_e *MockSourceAdapter_Expecter) FetchAlbum(ctx interface{}, parsed interface{}) *MockSourceAdapter_FetchAlbum_Call {
	return &MockSourceAdapter_FetchAlbum_Call{Call: _e.mock.On("FetchAlbum", ctx, parsed)}
}

func (_c *MockSourceAdapter_FetchAlbum_Call) Run(run func(ctx context.Context, parsed model.ParsedAlbumURL)) *MockSourceAdapter_FetchAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ParsedAlbumURL))
	})
	return _c
}

func (_c *MockSourceAdapter_FetchAlbum_Call) Return(_a0 *model.CanonicalAlbum, _a1 error) *MockSourceAdapter_FetchAlbum_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceAdapter_FetchAlbum_Call) RunAndReturn(run func(context.Context, model.ParsedAlbumURL) (*model.CanonicalAlbum, error)) *MockSourceAdapter_FetchAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAlbumURL provides a mock function with given fields: raw
func (_m *MockSourceAdapter) ParseAlbumURL(raw string) (*model.ParsedAlbumURL, error) {
	ret := _m.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for ParseAlbumURL")
	}

	var r0 *model.ParsedAlbumURL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ParsedAlbumURL, error)); ok {
		return rf(raw)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ParsedAlbumURL); ok {
		r0 = rf(raw)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ParsedAlbumURL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(raw)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSourceAdapter_ParseAlbumURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAlbumURL'
type MockSourceAdapter_ParseAlbumURL_Call struct {
	*mock.Call
}

// ParseAlbumURL is a helper method to define mock.On call
//   - raw string
func (_e *MockSourceAdapter_Expecter) ParseAlbumURL(raw interface{}) *MockSourceAdapter_ParseAlbumURL_Call {
	return &MockSourceAdapter_ParseAlbumURL_Call{Call: _e.mock.On("ParseAlbumURL", raw)}
}

func (_c *MockSourceAdapter_ParseAlbumURL_Call) Run(run func(raw string)) *MockSourceAdapter_ParseAlbumURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSourceAdapter_ParseAlbumURL_Call) Return(_a0 *model.ParsedAlbumURL, _a1 error) *MockSourceAdapter_ParseAlbumURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSourceAdapter_ParseAlbumURL_Call) RunAndReturn(run func(string) (*model.ParsedAlbumURL, error)) *MockSourceAdapter_ParseAlbumURL_Call {
	_c.Call.Return(run)
	return _c
}

// Service provides a mock function with no fields
func (_m *MockSourceAdapter) Service() model.ServiceName {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Service")
	}

	var r0 model.ServiceName
	if rf, ok := ret.Get(0).(func() model.ServiceName); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.ServiceName)
	}

	return r0
}

// MockSourceAdapter_Service_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Service'
type MockSourceAdapter_Service_Call struct {
	*mock.Call
}

// Service is a helper method to define mock.On call
func (_e *MockSourceAdapter_Expecter) Service() *MockSourceAdapter_Service_Call {
	return &MockSourceAdapter_Service_Call{Call: _e.mock.On("Service")}
}

func (_c *MockSourceAdapter_Service_Call) Run(run func()) *MockSourceAdapter_Service_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSourceAdapter_Service_Call) Return(_a0 model.ServiceName) *MockSourceAdapter_Service_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSourceAdapter_Service_Call) RunAndReturn(run func() model.ServiceName) *MockSourceAdapter_Service_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSourceAdapter creates a new instance of MockSourceAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceAdapter {
	mock := &MockSourceAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
